### PR TITLE
Fullwidth sections

### PR DESCRIPTION
**Pull request by vxsx**
fullwidth sections done with real elements have horizontal scroll and require overflow-x on body, which result in lots of bugs with scrolling on different browsers, this PR fixes that by using box-shadow for that.

### CODE REVIEW

**Comment by FinalAngel** [comment]
LGTM

**Comment by FinalAngel** [comment]
test should pass if you pull from master

**Comment by vxsx** [comment]
@FinalAngel didn't seem to help

**Comment by FinalAngel** [comment]
hrm you can merge then, I'll check it out later. Maybe something related to sekizai / reversion / classytags release

**Pull request merged**
