### PR TITLE
add bower.json to gitignore

### PR DESCRIPTION
**Pull request by vxsx**

### CODE REVIEW

**Comment by FinalAngel** [comment]
LGTM

**Comment by vxsx** [comment]
i'll have to figure out why is the travis failing

**Comment by vxsx** [comment]
ok, i figured it out
we didn't actually move dot files when installing the theme - that's why jscs was failing travis
i fixed installation and added other dotfiles to ignore

**Comment by FinalAngel** [comment]
thats weird, why does that suddenly fail? Previous builds didn't :/

LGTM

**Comment by vxsx** [comment]
@FinalAngel they actually were failing :)

**Pull request merged**
